export { APP_NAME, APP_FULL_NAME, APP_SUBTITLE, APP_PACKAGE, APP_VERSION, APP_VERSION_CODE, APP_ICON_BACKGROUND } from './constants'
export {
	DEVELOPER_NAME,
	DEVELOPER_WEBSITE,
	PRIVACY_POLICY_URL,
	PRIVACY_NOTES,
} from './privacy'
